/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program_sederhana_bagian2;

/**
 *
 * @author Lenovo
 */
public class data_siswa extends javax.swing.JFrame {

    /**
     * Creates new form data_siswa
     */
    public data_siswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cmbjurusan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbsepakbola = new javax.swing.JCheckBox();
        cbbadminton = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtfkeluaran = new javax.swing.JTextArea();
        btnproses = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtfalamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfkelas = new javax.swing.JTextField();
        cbsenitari = new javax.swing.JCheckBox();
        cbsenimusik = new javax.swing.JCheckBox();
        cbrenang = new javax.swing.JCheckBox();
        cbfutsal = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Data Siswa");

        jLabel2.setText("Nama");

        txtfnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnamaActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Kelamin");

        rblaki.setText("Laki-laki");
        rblaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblakiActionPerformed(evt);
            }
        });

        rbperempuan.setText("Perempuan");
        rbperempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbperempuanActionPerformed(evt);
            }
        });

        jLabel4.setText("Jurusan");

        cmbjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<---------Pilih Jurusan--------->", "RPL", "PKM", "AKL", "OTKP", "BDP" }));
        cmbjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjurusanActionPerformed(evt);
            }
        });

        jLabel5.setText("Hobi");

        cbsepakbola.setText("Sepak Bola");
        cbsepakbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsepakbolaActionPerformed(evt);
            }
        });

        cbbadminton.setText("Badminton");

        jLabel6.setText("Keluaran:");

        txtfkeluaran.setColumns(20);
        txtfkeluaran.setRows(5);
        jScrollPane1.setViewportView(txtfkeluaran);

        btnproses.setText("Proses");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });

        jLabel7.setText("Alamat");

        txtfalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfalamatActionPerformed(evt);
            }
        });

        jLabel8.setText("Kelas");

        txtfkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfkelasActionPerformed(evt);
            }
        });

        cbsenitari.setText("Seni Tari");
        cbsenitari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsenitariActionPerformed(evt);
            }
        });

        cbsenimusik.setText("Seni Musik");
        cbsenimusik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsenimusikActionPerformed(evt);
            }
        });

        cbrenang.setText("Renang");
        cbrenang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrenangActionPerformed(evt);
            }
        });

        cbfutsal.setText("Futsal");
        cbfutsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfutsalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(btnproses)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbrenang)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtfnama)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rblaki)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbperempuan))
                                .addComponent(cmbjurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtfalamat, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtfkelas, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbsepakbola)
                                        .addComponent(cbsenitari))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbsenimusik)
                                        .addComponent(cbbadminton)
                                        .addComponent(cbfutsal)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtfalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rblaki)
                            .addComponent(rbperempuan))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtfkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbsepakbola)
                            .addComponent(cbbadminton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbsenitari)
                    .addComponent(cbsenimusik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbrenang)
                    .addComponent(cbfutsal))
                .addGap(20, 20, 20)
                .addComponent(btnproses)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnamaActionPerformed

    private void rblakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblakiActionPerformed
        // TODO add your handling code here:
        rbperempuan.setSelected(false);
    }//GEN-LAST:event_rblakiActionPerformed

    private void cbsepakbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsepakbolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsepakbolaActionPerformed

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        // TODO add your handling code here:
        String Jenkel="";
        String hobi1="";
        String hobi2="";
        String hobi3="";
        String hobi4="";
        String hobi5="";
        String hobi6="";
        String jurusan=null;    
        
        //untuk menyimpan nilai dari radio button
        if (rblaki.isSelected())
        {
            Jenkel = rblaki.getText();
        }
        else
        {
            Jenkel = rbperempuan.getText();
        }
        
        // -------------------- batas --------------------
        
        //untuk enyimpan nilai dari combo box
        if (cmbjurusan.getSelectedItem()== "RPL")
        {
            jurusan = "Rekayasa Perangkat Lunak";
        }
        else if (cmbjurusan.getSelectedItem()=="PKM")
        {
            jurusan = "Perbankan dan Keuangan Mikro";
        }
        else if (cmbjurusan.getSelectedItem()=="AKL")
        {
            jurusan = "Akutansi dan Keuangan Lembaga";
        }
        else if (cmbjurusan.getSelectedItem()=="OTKP")
        {
            jurusan = "Otomatisasi dan Tata Kelola Perkantoran";
        }
        else if (cmbjurusan.getSelectedItem()=="BDP")
        {
            jurusan = "Bisnis Daring dan Pemasaran";
        }
        // -------------------- batas --------------------
        
        //untuk menyimpan nilai dari check box
        if (cbsepakbola.isSelected())
        {
            hobi1 = cbsepakbola.getText();
        }
        if (cbbadminton.isSelected())
        {
            hobi2 = cbbadminton.getText();
        }
        if (cbsenitari.isSelected())
        {
            hobi3 = cbsenitari.getText();
        }
        if (cbsenimusik.isSelected())
        {
            hobi4 = cbsenimusik.getText();
        }
        if (cbrenang.isSelected())
        {
            hobi5 = cbrenang.getText();
        }
        if (cbfutsal.isSelected())
        {
            hobi6 = cbfutsal.getText();
        }
        //-------------------- batas --------------------
        
        //untuk menyimpan nilai ke Text Area
        txtfkeluaran.setText("Nama \t: " + txtfnama.getText() +
                             '\n' + "Alamat \t: " + txtfalamat.getText() +
                             '\n' + "Jenis Kelamin \t: " + Jenkel +
                             '\n' + "Kelas \t: " + txtfkelas.getText() +
                             '\n' + "Jurusan \t: " + jurusan +
                             '\n' + "Hobi \t: " + hobi1 +
                             '\n' + "\t  " + hobi2 +
                             '\n' + "\t  " + hobi3 +
                             '\n' + "\t  " + hobi4 +
                             '\n' + "\t  " + hobi5 +
                             '\n' + "\t  " + hobi6
        );
    }//GEN-LAST:event_btnprosesActionPerformed

    private void rbperempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbperempuanActionPerformed
        // TODO add your handling code here:
        rblaki.setSelected(false);
    }//GEN-LAST:event_rbperempuanActionPerformed

    private void txtfalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfalamatActionPerformed

    private void txtfkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfkelasActionPerformed

    private void cbsenitariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsenitariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsenitariActionPerformed

    private void cbsenimusikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsenimusikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsenimusikActionPerformed

    private void cbrenangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrenangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbrenangActionPerformed

    private void cbfutsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfutsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbfutsalActionPerformed

    private void cmbjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbjurusanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnproses;
    private javax.swing.JCheckBox cbbadminton;
    private javax.swing.JCheckBox cbfutsal;
    private javax.swing.JCheckBox cbrenang;
    private javax.swing.JCheckBox cbsenimusik;
    private javax.swing.JCheckBox cbsenitari;
    private javax.swing.JCheckBox cbsepakbola;
    private javax.swing.JComboBox<String> cmbjurusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTextField txtfalamat;
    private javax.swing.JTextField txtfkelas;
    private javax.swing.JTextArea txtfkeluaran;
    private javax.swing.JTextField txtfnama;
    // End of variables declaration//GEN-END:variables
}
